services:
  jaero:
    image: ghcr.io/sdr-enthusiasts/docker-jaero:latest
    tty: true
    container_name: jaero
    hostname: jaero
    restart: unless-stopped
    ports:
    - 5800:5800
    - 30003:30003
    environment:
      - TZ=Australia/Melbourne
      - SET_STATION_ID=FEEDER-ID
      - DISABLE_PLANE_LOGGING=true
      - ENABLE_BASESTATION_FORMAT=false
      - BASESTATION_ADDRESS=0.0.0.0:30003
      - BEHAVE_AS_BASESTATION_CLIENT=false
      - SDRX_ADDRESS=sdrx.ip.address:6003
      - SDRX_TOPIC_NAME=VFO
      - NUMBER_OF_SDRX_TOPICS=3
      - ENABLE_FEEDING=true
      - FEEDERS=1\format=4 1\host=feed.airframes.io 1\port=5571 # 2\format=4 2\host=acarshub 2\port=5557
#    volumes:
#      - "BaseStation.sqb:/opt/jaero/basestation.sqb"
    tmpfs:
      - /run:exec,size=64M
      - /var/log,size=32M
      - /tmp:exec
