version: "3"

services:
  jaero:
    image: ghcr.io/sdr-enthusiasts/docker-jaero:latest
    tty: true
    container_name: jaero
    hostname: jaero
    restart: unless-stopped
    ports:
    - 5800:5800
    - 30003:30003
    environment:
      - TZ=Australia/Melbourne
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - VNC_PASSWORD=
      - SET_STATION_ID=FEEDER-ID
      - DISABLE_PLANE_LOGGING=true
      - ENABLE_BASESTATION_FORMAT=false
      - BASESTATION_ADDRESS=0.0.0.0:30003
      - BEHAVE_AS_BASESTATION_CLIENT=false
      - SDRX_ADDRESS=sdrx.ip.address:6003
      - SDRX_TOPIC_NAME=VFO
      - NUMBER_OF_SDRX_TOPICS=3
      - FEED_AIRFRAMES=true
#    volumes:
#      - "BaseStation.sqb:/opt/jaero/basestation.sqb"
    tmpfs:
      - /run:exec,size=64M
      - /var/log,size=32M
      - /tmp:exec
