#!/usr/bin/with-contenv bash
#shellcheck shell=bash  

export HOME=/config

umask 007
pulseaudio \
    --system \
  2>&1 | \
    # grep -v 'Failed to connect to system bus' | \
    stdbuf -o0 awk '{print "[pulseaudio] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
