#!/usr/bin/with-contenv bash
#shellcheck shell=bash

/usr/bin/Xvfb $DISPLAY -screen 0 ${DISPLAY_WIDTH}x${DISPLAY_HEIGHT}x24 \
  2>&1 | stdbuf -o0 awk '{print "[Xvfb] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 10
