#!/bin/bash

set -xe

STARTAPP=/startapp.sh

cat << EOF > ${STARTAPP}
HOME=/config
export HOME
EOF

for i in $(seq -f "%02g" 1 ${NUMBER_OF_SDRX_TOPICS}); do
    jaerostart=("/opt/jaero/JAERO -s ${SDRX_TOPIC_NAME}$i")
cat << EOF >> ${STARTAPP}
${jaerostart[@]} > /dev/null 2>&1 &
EOF
done

sed -i '$ s/.$//' ${STARTAPP}

chmod +x ${STARTAPP}

