#!/usr/bin/with-contenv bash
#shellcheck shell=bash

/usr/bin/x11vnc  \
    -display $DISPLAY \
    -rfbport 5900 \
    -rfbportv6 -1 -no6 -noipv6 -httpportv6 -1 \
    -forever \
    -desktop "JAERO" \
    -cursor arrow \
    -shared \
    $VNC_SECURITY \
    -nopw \
  2>&1 | stdbuf -o0 awk '{print "[x11vnc] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 10
