---
name: Deploy

on:
  workflow_dispatch:

  push:
    branches:
      - main
    # Don't trigger if it's just a documentation update
    paths:
      - "Dockerfile**"
      - "rootfs/**"

env:
  GHCR_IMAGE: sdr-enthusiasts/docker-jaero
  GHCR_REGISTRY: ghcr.io
  GH_LABEL: main
  GHCR_TAG: latest

jobs:
  workflow-dispatch:
    name: Triggered via Workflow Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Log dispatch reason
        env:
          INPUTS_REASON: ${{ github.event.inputs.reason }}
        run: |
          echo "Workflow dispatch reason: $INPUTS_REASON"

  deploy:
    name: Deploy 
    uses: sdr-enthusiasts/common-github-workflows/.github/workflows/build_and_push_image.yml@main
    with:
      push_enabled: true
      push_destinations: ghcr.io
      ghcr_repo_owner: ${{ github.repository_owner }}
      ghcr_repo: ${{ github.repository }}
      get_version_method: file_in_container:file=/CONTAINER_VERSION
      build_version_specific: false
      build_platform_specific: false
      build_nohealthcheck: false
      platform_linux_arm32v7_enabled: false
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

